name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using BAIDU QIANFAN API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  QIANFAN_AK:
    description: "QIANFAN AK."
    required: true
  QIANFAN_SK:
    description: "QIANFAN SK."
    required: true
  QIANFAN_MODEL:
    description: "QIANFAN API model."
    required: false
    default: "ERNIE-Speed-8K"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
