name: Code Review with Baidu Qianfan
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: ysh0566/qianfan-ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          QIANFAN_AK: ${{ secrets.QIANFAN_AK }}
          QIANFAN_SK: ${{ secrets.QIANFAN_SK }}
          QIANFAN_MODEL: "ERNIE-Speed-8K" # Optional: defaults to "ERNIE-Speed-8K". It's free to use.
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
